### ISSUE TITLE
Stop function

### ISSUE THREAD

**Issue by phan-dev** [shpak86/tcp_scanner#3]
We should support the "Stop" function to stop the scanning process.
@shpak86 @jahan-addison

**Comment by shpak86** [comment]
Hi, @phan-dev!
Unfortunately there are no ways to control scanning process. As a workaround you may split a range of scanning ports at a small subranges and scan each subrange one by one. If you decide to stop scanning process you'll need to wait until current subrange scanning will be finished and cancel all the next. Obviously this is just a temporary solution. 
Anyway the library should have the methods to control the scanning process. I'll add the controls to the library soon.

**Comment by phan-dev** [comment]
> Hi, @phan-dev!
> Unfortunately there are no ways to control scanning process. As a workaround you may split a range of scanning ports at a small subranges and scan each subrange one by one. If you decide to stop scanning process you'll need to wait until current subrange scanning will be finished and cancel all the next. Obviously this is just a temporary solution.
> Anyway the library should have the methods to control the scanning process. I'll add the controls to the library soon.

Thanks @shpak86 for the temporary solution.
I'm looking forward to see the new version!

**Comment by shpak86** [comment]
Hi!
I published a new version of the library. You should use new `TcpScannerTask` class which has `cancel()` method and allows you to take actual scan reports whenever you want.

**Comment by phan-dev** [comment]
@shpak86 
Thank you for kind support!
I got an issue: https://github.com/shpak86/tcp_scanner/pull/4#discussion_r677026348

**Comment by phan-dev** [comment]
@shpak86 
Another issue: https://github.com/shpak86/tcp_scanner/pull/4#discussion_r677769962
